-- MySQL Script generated by MySQL Workbench
-- Wed Mar 16 16:55:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Database_App
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Database_App` ;

-- -----------------------------------------------------
-- Schema Database_App
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Database_App` DEFAULT CHARACTER SET utf8 ;
USE `Database_App` ;

-- -----------------------------------------------------
-- Table `Database_App`.`Marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Database_App`.`Marca` ;

CREATE TABLE IF NOT EXISTS `Database_App`.`Marca` (
  `idMarca` INT NOT NULL AUTO_INCREMENT,
  `Nombre_m` VARCHAR(50) NOT NULL,
  `Telefono` VARCHAR(50) NOT NULL,
  `Correo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB


-- -----------------------------------------------------
-- Table `Database_App`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Database_App`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `Database_App`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NOT NULL,
  `Apellidos` VARCHAR(255) NOT NULL,
  `Asesor` VARCHAR(255) NOT NULL,
  `Sucursal` VARCHAR(255) NOT NULL,
  `Dia` VARCHAR(45) NOT NULL,
  `Mes` VARCHAR(45) NOT NULL,
  `Año` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Fecha_registro` VARCHAR(100) NOT NULL,
  `Notas` VARCHAR(255) NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC),
  INDEX `fk_Cliente_Marca1_idx` (`Marca_idMarca` ASC),
  CONSTRAINT `fk_Cliente_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `Database_App`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Database_App`.`Sucursal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Database_App`.`Sucursal` ;

CREATE TABLE IF NOT EXISTS `Database_App`.`Sucursal` (
  `idSucursal` INT NOT NULL AUTO_INCREMENT,
  `Nombre_s` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(255) NOT NULL,
  `Telefono` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  PRIMARY KEY (`idSucursal`),
  INDEX `fk_Sucursal_Marca1_idx` (`Marca_idMarca` ASC),
  CONSTRAINT `fk_Sucursal_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `Database_App`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Database_App`.`Sucursal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Database_App`.`Horario_Sucursal` ;

CREATE TABLE IF NOT EXISTS `Database_App`.`Horario_Sucursal` (
  `idHorario_Sucursal` INT NOT NULL,
  `daysOfWeek` VARCHAR(25) NOT NULL,
  `startTime` TIME NOT NULL,
  `endTime` TIME NOT NULL,
  `Sucursal_idSucursal` INT NOT NULL,
  PRIMARY KEY (`idHorario_Sucursal`),
  INDEX `fk_Horario_Sucursal_Sucursal1_idx` (`Sucursal_idSucursal` ASC),
  CONSTRAINT `fk_Horario_Sucursal_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `Database_App`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
-- -----------------------------------------------------
-- Table `Database_App`.`Membresia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Database_App`.`Membresia` ;

CREATE TABLE IF NOT EXISTS `Database_App`.`Membresia` (
  `idMembresia` INT NOT NULL AUTO_INCREMENT,
  `Folio_membresia` VARCHAR(50) NOT NULL,
  `Asesor_venta` VARCHAR(50) NOT NULL,
  `Fecha_compra` VARCHAR(100) NOT NULL,
  `Tratamiento` VARCHAR(200) NOT NULL,
  `Sucursal` VARCHAR(45) NOT NULL,
  `Acompañantes` VARCHAR(45) NOT NULL,
  `Ticket` VARCHAR(100) NOT NULL,
  `Importe_total` VARCHAR(100) NOT NULL,
  `Importe_t_tratamiento` VARCHAR(100) NOT NULL,
  `Descuento` VARCHAR(100) NOT NULL,
  `Notas` VARCHAR(255) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  PRIMARY KEY (`idMembresia`),
  INDEX `fk_Membresia_Cliente1_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Membresia_Marca1_idx` (`Marca_idMarca` ASC),
  CONSTRAINT `fk_Membresia_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `Database_App`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Membresia_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `Database_App`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Database_App`.`Cabina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Database_App`.`Cabina` ;

CREATE TABLE IF NOT EXISTS `Database_App`.`Cabina` (
  `Nombre` VARCHAR(255) NOT NULL,
  `idCabina` INT NOT NULL AUTO_INCREMENT,
  `Sucursal_idSucursal` INT NOT NULL,
  PRIMARY KEY (`idCabina`),
  INDEX `fk_Cabina_Sucursal1_idx` (`Sucursal_idSucursal` ASC),
  CONSTRAINT `fk_Cabina_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `Database_App`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Database_App`.`Tecnologia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Database_App`.`Tecnologia` ;

CREATE TABLE IF NOT EXISTS `Database_App`.`Cabina` (
  `Nombre` VARCHAR(255) NOT NULL,
  `idCabina` INT NOT NULL AUTO_INCREMENT,
  `Sucursal_idSucursal` INT NOT NULL,
  PRIMARY KEY (`idCabina`),
  INDEX `fk_Cabina_Sucursal1_idx` (`Sucursal_idSucursal` ASC),
  CONSTRAINT `fk_Cabina_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `Database_App`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB


-- -----------------------------------------------------
-- Table `Database_App`.`Servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Database_App`.`Servicio` ;

CREATE TABLE IF NOT EXISTS `Database_App`.`Servicio` (
  `Nombre` VARCHAR(255) NOT NULL,
  `Categoria` VARCHAR(255) NOT NULL,
  `Precio` VARCHAR(255) NOT NULL,
  `Duracion` VARCHAR(255) NOT NULL,
  `idServicio` INT NOT NULL AUTO_INCREMENT,
  `Tecnologia_idTecnologia` INT NULL,
  `Cabina_idCabina` INT NULL,
  `Marca_idMarca` INT NOT NULL,
  PRIMARY KEY (`idServicio`),
  INDEX `fk_Servicio_Tecnologia1_idx` (`Tecnologia_idTecnologia` ASC),
  INDEX `fk_Servicio_Cabina1_idx` (`Cabina_idCabina` ASC),
  INDEX `fk_Servicio_Marca1_idx` (`Marca_idMarca` ASC),
  CONSTRAINT `fk_Servicio_Tecnologia1`
    FOREIGN KEY (`Tecnologia_idTecnologia`)
    REFERENCES `Database_App`.`Tecnologia` (`idTecnologia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servicio_Cabina1`
    FOREIGN KEY (`Cabina_idCabina`)
    REFERENCES `Database_App`.`Cabina` (`idCabina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servicio_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `Database_App`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB


-- -----------------------------------------------------
-- Table `Database_App`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Database_App`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `Database_App`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(100) NOT NULL,
  `Sucursal_idSucursal` INT NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  PRIMARY KEY (`idUsuarios`),
  INDEX `fk_Usuarios_Sucursal1_idx` (`Sucursal_idSucursal` ASC),
  INDEX `fk_Usuarios_Marca1_idx` (`Marca_idMarca` ASC),
  CONSTRAINT `fk_Usuarios_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `Database_App`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `Database_App`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Database_App`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Database_App`.`Rol` ;

CREATE TABLE IF NOT EXISTS `Database_App`.`Rol` (
  `idRol` INT NOT NULL,
  `Tipo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Database_App`.`Calendario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Database_App`.`Calendario` ;

CREATE TABLE IF NOT EXISTS `Database_App`.`Calendario` (
  `idCalendario` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `resourceId` VARCHAR(100) NOT NULL,
  `start` DATETIME NOT NULL,
  `Nombre_c` VARCHAR(100) NOT NULL,
  `Apellidos` VARCHAR(100) NOT NULL,
  `Tratamiento` VARCHAR(45) NOT NULL,
  `Notas` VARCHAR(200) NOT NULL,
  `Sucursal_idSucursal` INT NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  PRIMARY KEY (`idCalendario`),
  INDEX `fk_Calendario_Sucursal1_idx` (`Sucursal_idSucursal` ASC),
  INDEX `fk_Calendario_Marca1_idx` (`Marca_idMarca` ASC),
  CONSTRAINT `fk_Calendario_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `Database_App`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calendario_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `Database_App`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

-- -----------------------------------------------------
-- Table `Database_App`.`Especialista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Database_App`.`Especialista` ;

CREATE TABLE IF NOT EXISTS `Database_App`.`Especialista` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `RS_FH` VARCHAR(45) NULL,
  `RS_FL` VARCHAR(45) NULL,
  `RS_FPP` VARCHAR(45) NULL,
  `RS_FAL` VARCHAR(45) NULL,
  `RS_DC` VARCHAR(45) NULL,
  `RS_FDM` VARCHAR(45) NULL,
  `RS_EN` VARCHAR(45) NULL,
  `RS_ME` VARCHAR(45) NULL,
  `RS_DP` VARCHAR(45) NULL,
  `RS_SL` VARCHAR(45) NULL,
  `RS_RS` VARCHAR(45) NULL,
  `RS_VF` VARCHAR(45) NULL,
  `RS_R` VARCHAR(45) NULL,
  `RS_SG` VARCHAR(45) NULL,
  `RS_DL` VARCHAR(45) NULL,
  `RS_SR` VARCHAR(45) NULL,
  `RS_LR` VARCHAR(45) NULL,
  `RS_NB` VARCHAR(45) NULL,
  `Rol_idRol` INT NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Especialista_Rol1_idx` (`Rol_idRol` ASC),
  INDEX `fk_Especialista_Usuarios1_idx` (`Usuarios_idUsuarios` ASC),
  CONSTRAINT `fk_Especialista_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `Database_App`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Especialista_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `Database_App`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB


-- -----------------------------------------------------
-- Table `Database_App`.`Horario_Especialista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Database_App`.`Horario_Especialista` ;

CREATE TABLE IF NOT EXISTS `Database_App`.`Horario_Especialista` (
  `idHorario_Especialista` INT NOT NULL AUTO_INCREMENT,
  `resourceId` INT NOT NULL,
  `startTime` TIME NOT NULL,
  `endTime` TIME NOT NULL,
  `daysOfWeek` INT NOT NULL,
  `Especialista_idEspecialista` INT NOT NULL,
  PRIMARY KEY (`idHorario_Especialista`),
  INDEX `fk_Horario_Especialista_Especialista1_idx` (`Especialista_idEspecialista` ASC),
  CONSTRAINT `fk_Horario_Especialista_Especialista1`
    FOREIGN KEY (`Especialista_idEspecialista`)
    REFERENCES `Database_App`.`Especialista` (`idEspecialista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Database_App`.`Usuarios_has_Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Database_App`.`Usuarios_has_Rol` ;

CREATE TABLE IF NOT EXISTS `Database_App`.`Usuarios_has_Rol` (
  `Usuarios_idUsuarios` INT NOT NULL,
  `Rol_idRol` INT NOT NULL,
  PRIMARY KEY (`Usuarios_idUsuarios`, `Rol_idRol`),
  INDEX `fk_Usuarios_has_Rol_Rol1_idx` (`Rol_idRol` ASC),
  INDEX `fk_Usuarios_has_Rol_Usuarios1_idx` (`Usuarios_idUsuarios` ASC),
  CONSTRAINT `fk_Usuarios_has_Rol_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `Database_App`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Rol_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `Database_App`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
